target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Precompiled Firestore SDK:
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '12.8.0'

  flutter_install_all_pods  File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end