#inspired by:
#https://canopas.com/automate-flutter-ios-app-deployment-with-github-actions-and-codemagic-cli-4d063ea6ef08
#https://blog.okaryo.studio/en/20240911-flutter-ios-firebase-app-distribution-github-actions-not-auto-signing/

### setup in appstoreconnect:
#if not exisiting yet, create a distribution certificate: https://mzansibytes.com/2021/08/28/create-apple-developer-certificates-on-windows/, then [Convert]::ToBase64String([IO.File]::ReadAllBytes("ExportedCertificate.pfx")) | Out-File "ExportedCertificate_base64.txt"

#create Identifier:  (APP-IDs/APP/) add Push Notifications, Sign In with Apple
#then change bundle id in Step 8 below
#create Provisioning Profile: Distribution/App Store Connect then [Convert]::ToBase64String([IO.File]::ReadAllBytes("AppName.mobileprovision")) | Out-File "AppName_base64.txt"
#copy Provisioning Profile name to Step 5 & 8 below
#create App in App Store Connect


### necessary github action repository secrets:
#TEAM_ID: https://appstoreconnect.apple.com/access/users

#from: https://appstoreconnect.apple.com/access/integrations/api:
#APPSTORE_ISSUER_ID
#APPSTORE_API_KEY_ID
#APPSTORE_API_PRIVATE_KEY: open p8 File with text editor and copy content //TODO with or without line breaks and start/end?

#BUILD_CERTIFICATE_BASE64 #distribution certificate in base64 format (can be the same for many apps)
#P12_PASSWORD #password for distribution certificate

#BUILD_PROVISION_PROFILE_BASE64

#KEYCHAIN_PASSWORD #can be set freely

###necessary github action repository variables:
#BUNDLE_ID
#PROVISIONING_PROFILE_NAME
#DEPLOYMENT_TARGET
#FLUTTER_VERSION

###make sure ios/Runner/ExportOptions-Template.plist exists
###make sure the bundle id in ios/Runner.xcodeproj/project.pbxproj is right and that the signing settings are set to manual and the correct provisioning profile is selected
#most of that should be set by the ExportOption.plist but are currently not, see https://github.com/flutter/flutter/issues/113977

name: iOS Build and Deploy

on:
  workflow_dispatch:

jobs:
  ios_deployment:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter SDK
      - name: Set up Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        env:
          FLUTTER_VERSION: ${{ vars.FLUTTER_VERSION }}
        with:
          channel: stable
          version: ${{ env.FLUTTER_VERSION }} # Keep this up to date with flutter --version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get
          flutter analyze --no-fatal-infos --no-fatal-warnings

      # Step 4: Initialize Keychain
      - name: Initialize Keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" $RUNNER_TEMP/app-signing.keychain-db
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $RUNNER_TEMP/app-signing.keychain-db
          security list-keychain -d user -s $RUNNER_TEMP/app-signing.keychain-db

      # Step 5: Configure Provisioning Profile
      - name: Configure Provisioning Profile
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          PROVISIONING_PROFILE_NAME: ${{ vars.PROVISIONING_PROFILE_NAME }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/$PROVISIONING_PROFILE_NAME.mobileprovision

      # Step 6: Configure Distribution Certificate
      - name: Configure Distribution Certificate
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > /tmp/certificate.p12
          security import /tmp/certificate.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $RUNNER_TEMP/app-signing.keychain-db
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $RUNNER_TEMP/app-signing.keychain-db

      # Step 7: Parse Build Number and Name from pubspec.yaml
      - name: Parse Build Number and Name
        id: version
        run: |
          VERSION_LINE=$(grep '^version:' pubspec.yaml)
          VERSION=$(echo $VERSION_LINE | cut -d' ' -f2 | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $VERSION_LINE | cut -d'+' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      # Step 8: Generate ExportOptions.plist from Template
      - name: Generate ExportOptions.plist
        env:
          EXPORT_METHOD: "app-store"
          EXPORT_DESTINATION: "export"
          BUNDLE_ID: ${{ vars.BUNDLE_ID }} # Change this when adapting to another app
          PROVISIONING_PROFILE: ${{ vars.PROVISIONING_PROFILE_NAME }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          envsubst < ios/Runner/ExportOptions-Template.plist > ios/Runner/ExportOptions.plist

#      # Step 8.5: Update iOS Deployment Target in Project Files
#      - name: Update iOS Deployment Target
#        env:
#          DEPLOYMENT_TARGET: ${{ vars.DEPLOYMENT_TARGET }}
#        run: |
#          # Update project.pbxproj
#          sed -i '' "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = $DEPLOYMENT_TARGET/g" ios/Runner.xcodeproj/project.pbxproj
#
#          # Update Podfile platform
#          sed -i '' "s/platform :ios, '[0-9]*\.[0-9]*'/platform :ios, '$DEPLOYMENT_TARGET'/g" ios/Podfile

      # Step 9: Build IPA
      - name: Build IPA
#        env:
          # These are forwarded by flutter -> xcodebuild
          #but apparently applies to ALL targets including the Pod libraries. But Pod libraries (frameworks) should use automatic signing
#          FLUTTER_XCODE_DEVELOPMENT_TEAM: ${{ secrets.TEAM_ID }}
##          FLUTTER_XCODE_CODE_SIGN_STYLE: "Manual"
#          FLUTTER_XCODE_PROVISIONING_PROFILE_SPECIFIER: ${{ vars.PROVISIONING_PROFILE_NAME }}
#          FLUTTER_XCODE_IPHONEOS_DEPLOYMENT_TARGET: ${{ vars.DEPLOYMENT_TARGET }}
#          FLUTTER_XCODE_PRODUCT_BUNDLE_IDENTIFIER: ${{ vars.BUNDLE_ID }}
          # optional if you want to pin the code sign identity:
#          FLUTTER_XCODE_CODE_SIGN_IDENTITY: "iPhone Distribution"
        run: |
          flutter build ipa \
            --release \
            --verbose \
            --build-number=$BUILD_NUMBER \
            --build-name=$VERSION \
            --export-options-plist=ios/Runner/ExportOptions.plist

      # Step 10: Create API Key File
      - name: Create API Key File
        env:
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.private_keys
          echo "$APPSTORE_API_KEY" > ~/.private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
          chmod 600 ~/.private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8

      # Step 11: Upload IPA to App Store Connect
      - name: Upload to App Store Connect
        env:
          API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          API_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          xcrun altool --upload-app -f build/ios/ipa/*.ipa -t ios --apiKey "$API_KEY_ID" --apiIssuer "$API_ISSUER_ID"

      # Check if release exists
      - name: Check Release
        id: check_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh release view "v$VERSION" 2>/dev/null; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi

      # Create release if it doesn't exist
      - name: Create Release if Not Exists
        id: create_release
        if: steps.check_release.outputs.release_exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$VERSION
          release_name: "Release v$VERSION"
          draft: true
          prerelease: false

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $(find $(pwd) -name "*.ipa")
          asset_name: PiusApp-v$VERSION.ipa
          asset_content_type: application/octet-stream

      # Step 13: Cleanup Keychain and Profiles
      - name: Cleanup
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm -rf ~/Library/MobileDevice/Provisioning\ Profiles
          rm -rf ~/.private_keys
